import { NextRequest, NextResponse } from 'next/server'

/*
 * CREDITFIX AUTOMATION
 * 
 * This endpoint handles:
 * 1. Dispute letter generation
 * 2. Automatic filing (future: connect to bureau APIs)
 * 3. Progress tracking
 * 4. Status updates
 */

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { 
      fullName, 
      address, 
      city, 
      state, 
      zip, 
      ssnLast4,
      bureau, 
      accountName, 
      accountNumber, 
      reason,
      email,
      phone 
    } = body

    // Generate dispute ID
    const disputeId = `CF-${Date.now().toString(36).toUpperCase()}`

    // In production, this would:
    // 1. Save to database (Supabase)
    // 2. Generate PDF letter
    // 3. Send confirmation email
    // 4. Queue for mailing (if Premium)
    // 5. Set up tracking for 30-day response

    // For now, return the generated letter and tracking
    const bureaus: Record<string, { name: string; address: string }> = {
      equifax: { name: 'Equifax', address: 'P.O. Box 740256, Atlanta, GA 30374' },
      experian: { name: 'Experian', address: 'P.O. Box 4500, Allen, TX 75013' },
      transunion: { name: 'TransUnion', address: 'P.O. Box 2000, Chester, PA 19016' },
    }

    const selectedBureau = bureaus[bureau as keyof typeof bureaus]
    const today = new Date().toLocaleDateString('en-US', { 
      month: 'long', 
      day: 'numeric', 
      year: 'numeric' 
    })

    const letter = `${selectedBureau.name}
${selectedBureau.address}

${today}

RE: Dispute of Inaccurate Information

To Whom It May Concern:

I am writing to dispute the following information on my credit report. I have identified the following item(s) as inaccurate or incomplete:

Account Name: ${accountName || '[Account Name]'}
Account Number: ${accountNumber || '[Account Number]'}

This information is inaccurate because: ${reason || '[Reason for dispute]'}

I am requesting that you investigate this matter and correct or delete the inaccurate information pursuant to the Fair Credit Reporting Act, Section 611.

I have attached copies of the following supporting documentation:
- Copy of driver's license or state ID
- Copy of Social Security card (last 4 digits visible)
- Proof of current address (utility bill or bank statement)

Please investigate this matter and provide me with written notification of the results of your investigation within 30 days as required by law.

Sincerely,

${fullName || '[Your Name]'}
${address || '[Your Address]'}
${city ? `${city}, ${state} ${zip}` : '[City, State ZIP]'}

${phone ? `Phone: ${phone}` : ''}
${email ? `Email: ${email}` : ''}

---
Dispute ID: ${disputeId}
Generated by CreditKlimb™
https://creditfix.com/dispute/${disputeId}
---`

    return NextResponse.json({
      success: true,
      disputeId,
      bureau: selectedBureau,
      letter,
      nextSteps: [
        'Print and sign the letter',
        'Attach copies of ID and proof of address',
        'Mail via certified mail to the bureau',
        'Wait up to 30 days for response',
        'Check your email for status updates',
      ],
      trackingUrl: `/dispute/${disputeId}`,
      estimatedResponse: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    })
  } catch (error: any) {
    console.error('Dispute error:', error)
    return NextResponse.json(
      { error: 'Failed to generate dispute' },
      { status: 500 }
    )
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const disputeId = searchParams.get('id')

  if (!disputeId) {
    return NextResponse.json(
      { error: 'Dispute ID required' },
      { status: 400 }
    )
  }

  // In production, fetch from database
  return NextResponse.json({
    disputeId,
    status: 'mailed',
    createdAt: new Date().toISOString(),
    estimatedResponse: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    updates: [
      { date: new Date().toISOString(), status: 'Letter generated', note: 'Ready to mail' },
    ]
  })
}